#!/bin/bash
#PBS -N hw2
#PBS -l walltime=00:20:00
#PBS -l nodes=1:ppn=1
#PBS -q edu_shared
#PBS -j oe
#PBS -V

#
## Move to the directory where the job was submitted
#
cd $PBS_O_WORKDIR
#
#  setup MPI programming environment
#
module load MPICH/3.3.2-GCC-9.3.0
#
# Run mpi job
#
mpirun -np $PBS_NP ./par_pi_op_simple_Utsav 20 $case
mpirun -np $PBS_NP ./par_pi_op_simple_Utsav 23 $case
mpirun -np $PBS_NP ./par_pi_op_simple_Utsav 26 $case
